name: Build Base Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Base image tag (e.g., latest, v1.0.0)'
        required: true
        default: 'latest'
        type: string
  push:
    paths:
      - 'Dockerfile.base'
      - '.github/workflows/build-base-image.yml'
  schedule:
    # Rebuild base image weekly to get security updates
    - cron: '0 2 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rails-base

jobs:
  build-base-image:
    name: Build and Push Base Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/khushibaby/rails-base
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.event.inputs.tag || 'latest' }}
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test base image
        run: |
          docker run --rm ghcr.io/khushibaby/rails-base:latest ruby --version
          docker run --rm ghcr.io/khushibaby/rails-base:latest node --version
          docker run --rm ghcr.io/khushibaby/rails-base:latest bundle --version

      - name: Generate build summary
        run: |
          echo "## Base Image Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: \`ghcr.io/khushibaby/rails-base\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**: \`${{ steps.meta.outputs.tags }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "- **Built at**: $(date -u)" >> $GITHUB_STEP_SUMMARY